"""add_haccp_non_conformites

Revision ID: 278dc7bb46b5
Revises: c343c764b2f0
Create Date: 2025-12-14 09:47:45.942202

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '278dc7bb46b5'
down_revision = 'c343c764b2f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non_conformite_haccp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('detectee_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_non_conformite', sa.String(length=120), nullable=False, comment='TEMP_HORS_SEUIL, DLC_DEPASSEE, etc.'),
    sa.Column('reference', sa.String(length=200), nullable=True, comment='Référence externe (ex: lot_id, equipement_id).'),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False, comment='OUVERTE/CLOTUREE'),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_corrective',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('non_conformite_id', sa.UUID(), nullable=False),
    sa.Column('creee_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('realisee', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['non_conformite_id'], ['non_conformite_haccp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_corrective')
    op.drop_table('non_conformite_haccp')
    # ### end Alembic commands ###
