"""migration_initiale

Revision ID: 53582036ad5f
Revises: 
Create Date: 2025-12-13 12:00:04.993680

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '53582036ad5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fournisseur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('unite_stock', sa.String(length=50), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('magasin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nom_affiche', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_table('commande_achat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('fournisseur_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('creee_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commande_achat_creee_le', 'commande_achat', ['creee_le'], unique=False)
    op.create_table('controle_haccp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('controle_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_controle', sa.String(length=120), nullable=False),
    sa.Column('resultat', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_controle_haccp_controle_le', 'controle_haccp', ['controle_le'], unique=False)
    op.create_table('equipement_thermique',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('type_equipement', sa.Enum('VITRINE', 'FRIGO', 'CHAMBRE_FROIDE', name='typeequipementthermique'), nullable=False),
    sa.Column('zone', sa.Enum('VENTE', 'CUISINE', 'PRODUCTION', name='zoneequipementthermique'), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_prevision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('creee_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_nettoyage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('realise_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_nettoyage_realise_le', 'journal_nettoyage', ['realise_le'], unique=False)
    op.create_table('lot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('fournisseur_id', sa.UUID(), nullable=True),
    sa.Column('code_lot', sa.String(length=120), nullable=True),
    sa.Column('date_dlc', sa.Date(), nullable=True),
    sa.Column('quantite_disponible', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magasin_id', 'ingredient_id', 'fournisseur_id', 'code_lot', name='uq_lot_magasin_ingredient_fournisseur_code')
    )
    op.create_index('ix_lot_date_dlc', 'lot', ['date_dlc'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_magasin_id', 'menu', ['magasin_id'], unique=False)
    op.create_table('plan_production',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('date_plan', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'VERROUILLE', 'TERMINE', name='statutplanproduction'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_production_date_plan', 'plan_production', ['date_plan'], unique=False)
    op.create_table('recette',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recette_magasin_id', 'recette', ['magasin_id'], unique=False)
    op.create_table('ligne_commande_achat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commande_achat_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commande_achat_id'], ['commande_achat.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligne_plan_production',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_production_id', sa.UUID(), nullable=False),
    sa.Column('recette_id', sa.UUID(), nullable=False),
    sa.Column('quantite_a_produire', sa.Float(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_production_id'], ['plan_production.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligne_prevision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_prevision_id', sa.UUID(), nullable=False),
    sa.Column('date_prevue', sa.Date(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('quantite_prevue', sa.Float(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_prevision_id'], ['execution_prevision.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ligne_prevision_date_prevue', 'ligne_prevision', ['date_prevue'], unique=False)
    op.create_table('ligne_recette',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recette_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_production',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('plan_production_id', sa.UUID(), nullable=True),
    sa.Column('recette_id', sa.UUID(), nullable=False),
    sa.Column('produit_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantite_produite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.ForeignKeyConstraint(['plan_production_id'], ['plan_production.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lot_production_produit_le', 'lot_production', ['produit_le'], unique=False)
    op.create_table('mouvement_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_mouvement', sa.Enum('RECEPTION', 'CONSOMMATION', 'AJUSTEMENT', 'PERTE', 'TRANSFERT', name='typemouvementstock'), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('reference_externe', sa.String(length=120), nullable=True),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mouvement_stock_horodatage', 'mouvement_stock', ['horodatage'], unique=False)
    op.create_table('reception_marchandise',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('fournisseur_id', sa.UUID(), nullable=False),
    sa.Column('commande_achat_id', sa.UUID(), nullable=True),
    sa.Column('recu_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commande_achat_id'], ['commande_achat.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reception_marchandise_recu_le', 'reception_marchandise', ['recu_le'], unique=False)
    op.create_table('releve_temperature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipement_thermique_id', sa.UUID(), nullable=False),
    sa.Column('releve_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipement_thermique_id'], ['equipement_thermique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_releve_temperature_releve_le', 'releve_temperature', ['releve_le'], unique=False)
    op.create_table('vente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('magasin_id', sa.UUID(), nullable=False),
    sa.Column('date_vente', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canal', sa.Enum('INTERNE', 'EXTERNE', 'AUTRE', name='canalvente'), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasin.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vente_date_vente', 'vente', ['date_vente'], unique=False)
    op.create_table('ligne_consommation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_production_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('mouvement_stock_id', sa.UUID(), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['lot_production_id'], ['lot_production.id'], ),
    sa.ForeignKeyConstraint(['mouvement_stock_id'], ['mouvement_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligne_reception_marchandise',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reception_marchandise_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('mouvement_stock_id', sa.UUID(), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['mouvement_stock_id'], ['mouvement_stock.id'], ),
    sa.ForeignKeyConstraint(['reception_marchandise_id'], ['reception_marchandise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ligne_reception_marchandise')
    op.drop_table('ligne_consommation')
    op.drop_index('ix_vente_date_vente', table_name='vente')
    op.drop_table('vente')
    op.drop_index('ix_releve_temperature_releve_le', table_name='releve_temperature')
    op.drop_table('releve_temperature')
    op.drop_index('ix_reception_marchandise_recu_le', table_name='reception_marchandise')
    op.drop_table('reception_marchandise')
    op.drop_index('ix_mouvement_stock_horodatage', table_name='mouvement_stock')
    op.drop_table('mouvement_stock')
    op.drop_index('ix_lot_production_produit_le', table_name='lot_production')
    op.drop_table('lot_production')
    op.drop_table('ligne_recette')
    op.drop_index('ix_ligne_prevision_date_prevue', table_name='ligne_prevision')
    op.drop_table('ligne_prevision')
    op.drop_table('ligne_plan_production')
    op.drop_table('ligne_commande_achat')
    op.drop_index('ix_recette_magasin_id', table_name='recette')
    op.drop_table('recette')
    op.drop_index('ix_plan_production_date_plan', table_name='plan_production')
    op.drop_table('plan_production')
    op.drop_index('ix_menu_magasin_id', table_name='menu')
    op.drop_table('menu')
    op.drop_index('ix_lot_date_dlc', table_name='lot')
    op.drop_table('lot')
    op.drop_index('ix_journal_nettoyage_realise_le', table_name='journal_nettoyage')
    op.drop_table('journal_nettoyage')
    op.drop_table('execution_prevision')
    op.drop_table('equipement_thermique')
    op.drop_index('ix_controle_haccp_controle_le', table_name='controle_haccp')
    op.drop_table('controle_haccp')
    op.drop_index('ix_commande_achat_creee_le', table_name='commande_achat')
    op.drop_table('commande_achat')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('magasin')
    op.drop_table('ingredient')
    op.drop_table('fournisseur')
    # ### end Alembic commands ###
