"""align_schema_referentiel

Revision ID: 6966f766d867
Revises: 53582036ad5f
Create Date: 2025-12-14 08:49:16.598529

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6966f766d867'
down_revision = '53582036ad5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu",
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Description courte pour l’affichage client",
        ),
    )

    op.add_column(
        "menu",
        sa.Column(
            "prix",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
            comment="Prix TTC en euros (provisoire)",
        ),
    )

    op.add_column(
        "menu",
        sa.Column(
            "commandable",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
            comment="Menu vendable / commandable côté client",
        ),
    )

    # cleanup defaults after backfill
    op.alter_column("menu", "prix", server_default=None)
    op.alter_column("menu", "commandable", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'commandable')
    op.drop_column('menu', 'prix')
    op.drop_column('menu', 'description')
    # ### end Alembic commands ###
