"""add_ingredient_cout_unitaire

Revision ID: c343c764b2f0
Revises: 6966f766d867
Create Date: 2025-12-14 09:24:22.772639

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c343c764b2f0'
down_revision = '6966f766d867'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredient",
        sa.Column(
            "cout_unitaire",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0"),
            comment="Coût unitaire dans l’unité de mesure (ex: €/kg, €/L, €/pièce)",
        ),
    )

    # Nettoyage du défaut (on ne veut pas de valeur en dur au niveau DB)
    op.alter_column("ingredient", "cout_unitaire", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'cout_unitaire')
    # ### end Alembic commands ###
