"""add commandes fournisseur

Revision ID: cd1233d73e50
Revises: 278dc7bb46b5
Create Date: 2025-12-14 10:57:55.071223

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cd1233d73e50'
down_revision = '278dc7bb46b5'
branch_labels = None
depends_on = None

# NOTE: migration amendée pour supporter la réception partielle.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commande_fournisseur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fournisseur_id', sa.UUID(), nullable=False),
    sa.Column('date_commande', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'ENVOYEE', 'PARTIELLE', 'RECEPTIONNEE', name='statut_commande_fournisseur'), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commande_fournisseur_date_commande', 'commande_fournisseur', ['date_commande'], unique=False)
    op.create_table('ligne_commande_fournisseur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commande_fournisseur_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('quantite_recue', sa.Float(), nullable=False, server_default=sa.text('0')),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commande_fournisseur_id'], ['commande_fournisseur.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ligne_commande_fournisseur')
    op.drop_index('ix_commande_fournisseur_date_commande', table_name='commande_fournisseur')
    op.drop_table('commande_fournisseur')
    # ### end Alembic commands ###
